name: Build theme

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build dist assets
        run: npm run build

      - name: Create theme zip
        run: |
          THEME_DIR="jose-portfoliov2"
          ZIP_NAME="${THEME_DIR}.zip"

          mkdir -p build
          rsync -av \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            --exclude "*.log" \
            --exclude ".DS_Store" \
            ./ build/${THEME_DIR}/

          cd build
          zip -r "../${ZIP_NAME}" "${THEME_DIR}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jose-portfoliov2
          path: jose-portfoliov2.zip
          if-no-files-found: error